---
abstract: 'Chocolate Perl for Win32 (EXPERIMENTAL)'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  LWP::Online: 1.07
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Perl::Dist::Chocolate
name: Perl-Dist-Chocolate
no_index:
  directory:
    - inc
    - t
requires:
  Perl::Dist::Strawberry: 1.07
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.07
